name: Desktop CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-2019, ubuntu-latest, macos-latest]
        arch: [x86, x64]
        include:
          - os:  windows-2019
            arch: x64
            generator: VS16Win64
            artifact: Release/BoxAssist.dll
          - os:  windows-2019
            arch: x86
            generator: VS16Win32
            artifact: Release/BoxAssist.dll
          - os: ubuntu-latest
            generator: Ninja
            artifact: libBoxAssist.so
          - os: macos-latest
            generator: Ninja
            artifact: libBoxAssist.dylib
        exclude:
          - os: ubuntu-latest
            arch: x86
          - os: macos-latest
            arch: x86

    steps:
      - uses: actions/checkout@v3
      
      - run: sudo apt install uuid-dev
        if: matrix.os == 'ubuntu-latest'
      
      - uses: lukka/run-cmake@v2
        id: runcmake_cmd
        with:
          buildDirectory: ${{ runner.workspace }}/build
          cmakeGenerator: ${{ matrix.generator }}
          cmakeBuildType: Release

      - uses: actions/upload-artifact@v3
        with:
          name: libs
          path: ${{ runner.workspace }}/build/${{ matrix.artifact }}
